---

- name: Create base directories (/dockers/config and /dockers/downloads)
  file:
    name: "{{ item }}"
    state: directory
    mode: 0755
    owner: kevinp
    group: kevinp
  loop:
    - "{{ rootcfg }}"
    - "{{ rootdnld }}"

- name: Create application directories
  file:
    name: "{{ item }}"
    state: directory
    mode: 0755
    owner: kevinp
    group: kevinp
  loop:
    - "{{ application_dirs }}"

- name: Create all application sub-dirs to store docker-compose.yml files
  file:
    name: "{{ docker_compose_store }}/{{ item.name }}"
    state: directory
    mode: 0755
    owner: root
    owner: root
  loop: "{{ application_list }}"

- name: Copy application specific docker-compose.yml files
  template:
    src: "docker-compose-{{ item.name }}.yml.j2"
    dest: "{{ docker_compose_store }}/{{ item.name }}/docker-compose.yml"
    mode: 0755
    owner: root
    group: root
  loop: "{{ application_list }}"


