---

- name: Copy application specfic .service files
  template:
    src: docker-compose-systemd-template.service.j2
    dest: "/etc/systemd/system/{{ item.name }}.service"
  loop: "{{ application_list }}"

- name: SystemD daemon re-load
  systemd:
    daemon_reload: true
